name: Check Partants Automatique

on:
  schedule:
    # Lancement tous les matins à 7h00 UTC (8h00 ou 9h00 en France)
    - cron: '0 7 * * *'
  workflow_dispatch: # Permet un lancement manuel

jobs:
  build:
    runs-on: ubuntu-latest
    environment: login # Lien avec tes secrets
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installation de Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installation des dépendances
        run: |
          pip install selenium webdriver-manager

      - name: Exécution du script
        env:
          FG_PASSWORD: ${{ secrets.FG_PASSWORD }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_DEST: ${{ secrets.EMAIL_DEST }}
        run: python scraper.py

      - name: Sauvegarder les captures d'écran
        uses: actions/upload-artifact@v4
        if: always() # <--- FORCE le téléchargement même si le script a réussi
        with:
          name: selenium-screenshots
          path: debug_*.png
          retention-days: 5 # Optionnel : garde les images 5 jours
