name: Automatisation France Galop (Quotidien & Hebdo)

on:
  schedule:
    # 1. Lancement quotidien pour scraper.py (7h00 UTC)
    - cron: '0 7 * * *'
    # 2. Lancement hebdomadaire pour gain.py (Lundi 8h00 UTC)
    - cron: '0 8 * * 1'
  workflow_dispatch: # Permet de lancer manuellement depuis l'onglet Actions

jobs:
  france-galop-tasks:
    runs-on: ubuntu-latest
    environment: login # Indispensable pour accéder à vos secrets
    
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installation de Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installation des dépendances
        run: |
          pip install selenium webdriver-manager

      - name: Exécution du Scraper Quotidien (Partants)
        if: github.event.schedule == '0 7 * * *' || github.event_name == 'workflow_dispatch'
        env:
          FG_PASSWORD: ${{ secrets.FG_PASSWORD }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_DEST: ${{ secrets.EMAIL_DEST }}
        run: python scraper.py

      - name: Exécution du Rapport Hebdomadaire (Gain/Top 4)
        if: github.event.schedule == '0 8 * * 1' || github.event_name == 'workflow_dispatch'
        env:
          FG_PASSWORD: ${{ secrets.FG_PASSWORD }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_DEST: ${{ secrets.EMAIL_DEST }}
        run: python gain.py

     ## - name: Sauvegarder les captures d'écran (Debug)
#        uses: actions/upload-artifact@v4
#        if: always() # S'exécute même si un script échoue
#        with:
#          name: selenium-screenshots
#          path: debug_*.png
#          retention-days: 5

          
